### ISSUE TITLE
bad quality and rtf

### ISSUE THREAD

**Issue by jeffery-work** [lesterphillip/SVCC23_FastSVC#11]
Excuse me, I wonder if this re-implement is consistent with the “fast svc” paper. 
I not only use the pre-train model in this repo but also re-train a model, both of their generate output result is terrible. Much far from the audio demo shown in "https://nobody996.github.io/FastSVC/".
And the rtf in the fast svc paper is about 0.25 on Intel(R) Xeon(R) E5-2680(v4) CPU @ 2.40GHz, but on my macpro, the end-to-end rtf is near 1.0. It's hard to be real-time.
Could share more details about the conversion quality and rtf ?
Thanks.

**Comment by lesterphillip** [comment]
Hi, some of the samples of my re-implementation can be found here: https://drive.google.com/drive/folders/1VDlyQDsvZZ2UujfY3axnUoKeCBM-h-Kx

I haven't checked the RTF so I can't say that part is consistent with the original paper. The quality needs work and I added some issues in #2  to improve it. 

Training takes a long time because of the E2E structure, so I haven't gotten the time to do it. If I get some time in the next few weeks I'll try to train a model.

**Comment by lesterphillip** [comment]
Most of the differences with the original paper can be found in the main README file, which are causing the metallic-like sounds.
If you have any other suggestions/questions, please ask them in the issue I mentioned above. Thank you.
