### ISSUE TITLE
Baseline models

### ISSUE THREAD

**Issue by GuangkeChen** [lesterphillip/SVCC23_FastSVC#9]
Hello, thanks a lot for the challenge and the released code.

I have a question about the baseline models:

In the arxiv paper, it said that B01 is similar to DiffSVC, while B02 is the decomposed FastSVC system. 

In this repository, two models are provided, i.e., fastsvc1 and B02. 

I wonder if the B01 model in the paper is the fastsvc1 model in the repository or if the code of B01 is not provided. Also, is B02 model in the paper exactly the B02 model in the repository?

Thanks for your help.

**Comment by lesterphillip** [comment]
Hi, SVCC's B01 is not in this repository as it cannot be open-sourced.

We made an unofficial re-implementation of FastSVC and the code for SVCC's B02 on the other hand is in this repository. B02 was just made to make training faster, since the end-to-end system in FastSVC takes a long time to train.
